### ISSUE TITLE
Research: Twitter API

### ISSUE THREAD

**Issue by dschoeni** [gmazlami/adv_se_project#1]
Find out whether there are any rate limitations for the API, what endpoints/queries could be used to support the sentiment analysis and in what format the data is delivered.

**Comment by Clabfabs** [comment]
After some research, I think I have some ideas now:
* Generally, to try out the API: [API Console] (https://dev.twitter.com/rest/tools/console)
* To query tweets: [search/tweets] (https://dev.twitter.com/rest/reference/get/search/tweets)
* Twitter proposes the following NodeJS client: [TwitterJSClient](https://github.com/BoyCook/TwitterJSClient). I don't really get our pre-configured project yet, but I remember that there is a service to authentificate to twitter. However, I think using the recommended Twitter Client probably works better here.
* Not quite sure how much the rate limitations affect us when we send one request that returns a lot of data, but there are limitations: [Rate limits](https://dev.twitter.com/rest/public/rate-limiting) | [Chart](https://dev.twitter.com/rest/public/rate-limits)
* Data is delivered in [JSON](https://dev.twitter.com/rest/public).
* Twitter has some [advice](https://dev.twitter.com/overview/general/things-every-developer-should-know) for programmers considering their API

They always note that it's not guaranteed that we get all the tweets with the [REST API](https://dev.twitter.com/rest/public), but the most recent and/or the most popular. For greater purposes, we shall use the [Streaming API](https://dev.twitter.com/streaming/overview). In my opinion, getting real-time data with streams is an overkill and we are good with the most recent/popular... But what do you think? Am I getting something completely wrong here? :)

**Comment by joe4dev** [comment]
I've started with the (very simple) sample application I've cited in the Wiki (http://www.ibm.com/developerworks/library/wa-nodejs-app/) and guess that we have to use the streaming API. See "Twitter’s Stream interface is perfect for observing trends in sentiment, since it allows access to all of the Twitter content on a topic over time."
Need Twitter app credentials to finish tutorial => See [#5](../issues/5)

**Comment by joe4dev** [comment]
Moved summary of Twitter docs to the Wiki because it is easier to access and edit there.
