### ISSUE TITLE
Map reduce aggregation

### ISSUE THREAD

**Issue by joe4dev** [gmazlami/adv_se_project#14]
* Extend Domi's prototype with a simple MongoDB MapReduce job that aggregates sentiment values in a meaningful way
* How could such an aggregation be optimized (e.g., consider time windows and change over time)

**Comment by Clabfabs** [comment]
I couldn't get my hands off that, since my last commit was kind of suboptimal for mapReduce-purposes. Now all the sentiment values are stored (not updated per phrase), and after a worker has analyzed x tweets, it aggregates the existing tweets and stores the data in the collection "aggregated".
