### ISSUE TITLE
Investigate Twitter streaming API properties

### ISSUE THREAD

**Issue by joe4dev** [gmazlami/adv_se_project#16]
* How can we dynamically add additional terms to an existing stream? How often? Might we get blocked by Twitter (any experiences on the web)?
* Should we think about using multiple Twitter apps/accounts? Are there any restrictions regarding IPs (e.g., only single stream from a unique IP)?
* Are streams stable over time or do they regularly break?

**Comment by Clabfabs** [comment]
I'll try to get the "dynamically add additional terms"-part done until saturday, ok?

**Comment by LilianaB** [comment]
- With the streamer you cannot establish connection in response to request (ex: add new terms to query)
- A few dozen connection attempts from time to time will not trigger a rate limit.
- twitter’s servers will hold the connection open indefinitely.
- If your client is rate limited frequently-> IP blocked for indeterminate time

we must be careful when adding terms
