### ISSUE TITLE
Research: Sentiment Analysis

### ISSUE THREAD

**Issue by dschoeni** [gmazlami/adv_se_project#2]
How can we implement:

* What types of analysis are there?
* How could we rate tweets?
* Sentiment Analysis for NodeJS?
* Are there already existing packages/solutions?

**Comment by joe4dev** [comment]
See [[Sentiment Analysis|Sentiment Analysis]]
* We can use the recommended framework from the project description
* There is already a sample app available. I've done the tutorial, updated some legacy stuff (though still very hacky :( )
